In [93]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import cv2
import sys
from kmeans import k_means

In [177]:
img = cv2.imread("cr7.png")
aux = img.shape
l = img.reshape(aux[0]*aux[1], 3)
df = pd.DataFrame(data = l)
dfo = pd.DataFrame(data = l)

In [192]:
k = 7
clusters_indexes, centroids, clusters = k_means(l, k)

16

In [193]:
for i in range(k):
    df.loc[clusters_indexes[i]] = centroids[i]


In [194]:
l2 = df.to_numpy()
img2 = l2.reshape(img.shape)
cv2.imwrite("img_change.png", img2) 
cv2.imshow("image", img2)
cv2.waitKey(0)

-1

In [195]:
print(centroids)

[[ 28.17165261  13.28299049 233.38879639]
 [  5.08281032   3.58612273 135.36488842]
 [133.72866217 163.19620881 206.37842398]
 [ 61.26590222  63.2839915   64.64399844]
 [ 43.24675455  32.7219061   14.26116608]
 [ 81.134897    98.79259637 109.51064654]
 [ 90.12165614  64.15042344  10.63792176]]


In [196]:
x =- np.full(
  shape=10000,
  fill_value=0
)
df2 = pd.DataFrame(data = x)
df2[1] = x
df2[2] = x

In [197]:
j = 0
for c in centroids:
    for i in range(10000):
        df2.loc[i] = c
    
    l3 = df2.to_numpy()
    img3 = l3.reshape((100,100,3))
    cv2.imwrite("color_"+ str(j) +".png", img3) 
    j = j+1

In [201]:
y = 0
for x in clusters_indexes:
    print(len(x))
    y = y + len(x)



18619
5736
10076
69157
69944
49030
14878


In [152]:
x = dfo.value_counts()

In [153]:
x

0    1    2  
0    0    0      704448
177  162  127     23601
178  163  128     21379
177  162  128     19581
     163  128     19265
                  ...  
126  82   96          1
          95          1
125  126  192         1
     124  191         1
238  220  174         1
Name: count, Length: 8715, dtype: int64

In [146]:
for i in range(10000):
    df2.loc[i] =[225.18433407, 205.39587705, 152.98128483]

In [147]:
l3 = df2.to_numpy()
img3 = l3.reshape((100,100,3))
cv2.imwrite("color_"+ str(100000000) +".png", img3) 

True

In [166]:
img = cv2.imread("cr7.png")

In [202]:
aux = img.shape

In [203]:
aux

(371, 640, 3)

In [204]:
371*640

237440